# Problem A (EASY)
print ("Hello World I am Using Python")
# Problem B (EASY)
print ("Язык программирования \"Python\"")
# Problem C (EASY)
print ("Я услышала стук в дверь: \n-Зачем вы явились? \nБорис ответил: \n-Принес посылку.")
# Problem A (MEDIUM)
print ("*")
print ("*" * 2)
print ("*" * 3)
print ("*" * 4)
print ("*" * 5)
#  Problem B (MEDIUM)
print ("Python" + "great" + "programming" + "language")
#  Problem B (HARD)
print (27 % 8)
print (255 // 4)
print (2 ** 5)
